FROM node:16-alpine

WORKDIR /devops-server
COPY ./ ./
RUN npm install
EXPOSE 3003

## Add the wait script to the image
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

RUN npm run test
CMD npm start